### ISSUE TITLE
Unity Message not coming to Flutter app

### ISSUE THREAD

**Issue by 6fried** [learntoflutter/flutter_embed_unity#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Unity version

- [X] I am using Unity 2022.3 LTS

### Common issues

- [X] I have checked the common issues

### Flutter version

3.13.9

### Description

When sending messages from flutter, everything's doing well. But when it comes to send a message from Unity, my Flutter app doesn't receive the message. I've created a new project and tried the configuratino again and everything worked perfectly. But when I go back to my existing app, I have the same problème. I'm sure it is a problem with my project but actually, I can't figure out what exactly is the proble.

### Minimum reproducible example (MRE)

I've created an empty Unity project, only purposed to test the mesaging feature

Unity project
<img width="1279" alt="image" src="https://github.com/learntoflutter/flutter_embed_unity/assets/56310541/bca96f21-d401-4959-9265-2b342921671f">
C# code
<img width="531" alt="image" src="https://github.com/learntoflutter/flutter_embed_unity/assets/56310541/3af15deb-7f23-4b28-a3b2-309debd7e632">
Flutter code
<img width="474" alt="image" src="https://github.com/learntoflutter/flutter_embed_unity/assets/56310541/0865593b-95f7-46b6-b2e2-1c466e748f81">

### What platforms are you seeing the problem on?

Android

**Comment by jamesncl** [comment]
Hi! This sounds like a Unity support question rather than an issue with this package. But here's a few things I can suggest you try to help debug the problem:

- Are you sure `OnSceneLoaded` is being called? (Try adding a `Console.Log` and check in Unity editor that it get's called)
- Are you sure that `SceneLoadMessenger` is attached to a Game Object in the scene?
- In Build Settings, is this scene the first scene in the list of Active Scenes?
- It might be possible that OnSceneLoaded is being called before Flutter is ready to receive it somehow - what happens if you add a delay before using `SendToFlutter`?
- Have you tried sending a message on `Awake` or on `Start`?

**Comment by 6fried** [comment]
Hello !

I've tried every steps suggested, but the problem is still there. And as mentionned earlier, I used the same project with the same configuration for an empty flutter project and everything worked fine. I'm then sure that the problem is in my app. As it's an advanced app, I can't figure out what could have caused the problem. That's why I'm asking for hints about what could have caused the problem.

**Comment by jamesncl** [comment]
The only other thing I can think of is to make sure you only have one `EmbedUnity` widget in your Flutter app, because by default messages will only go to the last `EmbedUnity` widget in the stack - see [using more than one instance of EmbedUnity](https://github.com/learntoflutter/flutter_embed_unity/tree/main/flutter_embed_unity#using-more-than-one-instance-of-embedunity).

Other than that, it's difficult to know what to suggest. Here's some pointers to learn more about how the message passing works from Unity to Flutter. It varies depending on if you are using Android or iOS:

- [SendToFlutter.cs](https://github.com/learntoflutter/flutter_embed_unity/blob/main/example_unity_2022_3_project/Assets/FlutterEmbed/SendToFlutter/SendToFlutter.cs) is where the message sending starts
- For iOS, it then goes to [SendToFlutter.swift](https://github.com/learntoflutter/flutter_embed_unity/blob/main/flutter_embed_unity_2022_3_ios/ios/Classes/Messaging/SendToFlutter.swift)
- For Android, it goes to [SendToFlutter.kt](https://github.com/learntoflutter/flutter_embed_unity/blob/main/flutter_embed_unity_2022_3_android/android/src/main/kotlin/com/learntoflutter/flutter_embed_unity_android/messaging/SendToFlutter.java)
- In both cases, Android and iOS send the message via Flutter's [Platform channels ](https://docs.flutter.dev/platform-integration/platform-channels)system to [UnityMessageListeners.dart](https://github.com/learntoflutter/flutter_embed_unity/blob/main/flutter_embed_unity/lib/src/unity_message_listeners.dart), which creates a platform channel listener for every `EmbedUnity` widget

You could fork the package and add some of your own logging statements, or consult the wiki on how to run the debugger against the examples (except you could replace the example Unity project with your own)

I'll close this issue as it doesn't seem to be an issue with the package but feel free to comment further
