### ISSUE TITLE
Safe Area in Unity Not Applied in Flutter Integration

### ISSUE THREAD

**Issue by GreejeshGajera** [learntoflutter/flutter_embed_unity#20]
**Flutter version**
3.22.1

flutter_embed_unity: ^1.0.4

**Unity version**
2022.3.28f1

**Description**
I'm experiencing an issue where the safe area set in Unity is not being respected when integrating Unity within a Flutter application. Other features of the integration are working as expected, but the safe area configuration from Unity is ignored, causing layout issues on devices with notches or other screen insets.

**Steps to Reproduce:**

- Create a Unity project and configure the safe area using the Screen.safeArea API.
- Build the Unity project for Android/iOS.
- Create a Flutter project and integrate the Unity module using the flutter_unity_widget package.
- Run the Flutter application on a device with a notch or other screen insets.

**Expected Behavior:**
The Unity view should respect the safe area set within Unity, ensuring that content is not obscured by notches or other screen insets.

**Actual Behavior:**
The Unity view does not respect the safe area configuration. Content extends into areas that should be padded according to the safe area settings, leading to potential usability issues.

**Comment by jamesncl** [comment]
Thanks for the bug report!

My first thoughts are that this may be difficult to fix (however there is a relatively simple work around - see below). The reason is that the "export as a library" feature of Unity expects Unity to be running inside a very specific Android activity: [UnityPlayerActivity](https://docs.unity3d.com/Manual/AndroidUnityPlayerActivity.html). However, to get Unity to run inside Flutter (which Unity was never designed to do), we have to hack around this, and instead run Unity within the context of [FlutterActivity](https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterActivity.html). I'm guessing that his is why the Unity SafeArea API isn't working - it probably tries to call UnityPlayerActivity to get the safe area, and gets no response.

There is probably a way to fix this, but will need significant work as the internals of how UnityPlayer works and deals with safe area is undocumented, and may change. Instead, I wondered if you could work around this by getting the safe area padding within Flutter, and passing it to Unity - something like this:

```dart
class Example extends StatelessWidget {

  const Example();

  @override
  Widget build(BuildContext context) {
    final safeAreaPadding = MediaQuery.paddingOf(context);
    return EmbedUnity(
      onMessageFromUnity: (String message) {
        if(message == "scene_loaded") {
          sendToUnity(
            "SafeAreaManager", 
            "SafeAreaReceivedFromFlutter", 
            jsonEncode({
              "top": safeAreaPadding.top,
              "bottom": safeAreaPadding.bottom,
              "left": safeAreaPadding.left,
              "right": safeAreaPadding.right,
            })
          );
        }
      },
    );
  }
}
```

Let me know what you think.

This appears to also affect `flutter_unity_widget` and has been raised in [a similar issue](https://github.com/juicycleff/flutter-unity-view-widget/issues/773) - it's also discussed [on this Unity forums thread](https://forum.unity.com/threads/using-unity-as-a-library-in-native-ios-android-apps.685195/page-3#post-6988628)

**Comment by GreejeshGajera** [comment]
I wanted to extend a heartfelt thank you for your swift and effective resolution of the safe area issue I was experiencing with the Unity integration in my Flutter application. Your assistance was invaluable, and everything is now working perfectly.
