### ISSUE TITLE
Can't build with Firebase Unity SDK: Framework not found FBLPromises

### ISSUE THREAD

**Issue by nguyenquynh201** [learntoflutter/flutter_embed_unity#8]
<img width="1404" alt="image" src="https://github.com/learntoflutter/flutter_embed_unity/assets/80728170/68e2253c-c643-4cbf-ba8e-dcfde7911054">

**Comment by learntoflutter** [comment]
Thanks for the bug report. I'm seeing quite a lot of discussions of this error on Unity forums and Stackoverflow:

- (Build error on xcode, Framework not found FBLPromises, (using firebase notification))[https://forum.unity.com/threads/build-error-on-xcode-framework-not-found-fblpromises-using-firebase-notification.1260806/]
- (Framework not found FBLPromises)[https://forum.unity.com/threads/framework-not-found-fblpromises.1426836/]
- [FBLPromises Framework not found](https://stackoverflow.com/questions/61510333/fblpromises-framework-not-found)
- [Framework not found FBLPromises Problem with Pods](https://stackoverflow.com/questions/70318761/framework-not-found-fblpromises-problem-with-pods)
- [Framework not found FBLPromises](https://stackoverflow.com/questions/68235136/framework-not-found-fblpromises)
- [Framework not found FBLPromises Error when using Xcode export](https://github.com/google-ar/arcore-unity-extensions/issues/73)

Have you tried the solutions posted there? The following suggestions seem to work for others:
- Make sure you are opening the .xcworkspace file instead of the .xcodeproj file and building from that Xcode Workspace
- Make sure cocoapods is up to date (`[sudo] gem install cocoapods`)
- Try running `pod install` manually 
- Clean the build folder
- Completely reset pods (`pod deintegrate`, then `pod cache clean --all`, then `flutter pub get`, then `pod install` and `pod update`

**Comment by nguyenquynh201** [comment]
I solved it by adding the pods file from the unity render project. I think in the example you missed a step.

**Comment by nguyenquynh201** [comment]
Because I followed your instructions in README but it didn't work and I added the pods file the same way I added the runner file and it worked.

**Comment by jamesncl** [comment]
Thank you but I still don't know exactly what you mean:

- What is "the pods file"? What is its filename? Where did you get it from?
- What exactly (step by step) do you mean by "added the pods file"?

**Comment by jamesncl** [comment]
Also, can you share what packages you have enabled in your Unity project? (go to Window -> Package Manager and show the packages in your project). I'm guessing that FBLPromises may come from a package you are using

**Comment by nguyenquynh201** [comment]
I think because my unity project uses firebase, when I export to the ios project, the firebase framework is in the project's pods file. When I add the unity-phone file to my main project, it cannot find the firebase framework. I tried to explain and hope you understand what I mean

**Comment by jamesncl** [comment]
Thank you. I think I understand. Can you please share the full contents of the following files as text:

* `<your flutter project>/ios/Podfile` (please indicate the changes you have made)
* `<your flutter project>/ios/unityLibrary/Podfile`

I can then add this information to the README as a common issue to help others

**Comment by jamesncl** [comment]
After some research I can now reproduce this error with the following steps:

1. [Download the Firebase Unity SDK](https://firebase.google.com/docs/unity/setup#add-sdks)
2. Open the example Unity project
3. In Unity, go to Assets -> Import package -> Custom package, select FirebaseCrashlytics.unityPackage
4. In Unity, go to Flutter Embed -> Export project to Flutter app (IOS), and do the [required setup steps from the flutter_embed_unity readme](https://pub.dev/packages/flutter_embed_unity#link-exported-unity-project-to-your-flutter-project)
5. Try to build the project - it will fail with build error 'Framework not found FBLPromises'

Unfortunately after lots of experimenting I can't figure out how to resolve this. Adding the Firebase SDK causes a Podfile to be included in the exported Unity-iPhone Xcode project with the following:

```
target 'UnityFramework' do
  use_frameworks!
  use_modular_headers!
  pod 'Firebase/Core', '10.15.0'
  pod 'Firebase/Crashlytics', '10.15.0'
end
```

So, these extra pods are required by the Firebase SDK. However, our Runner project does not have a UnityFramework target (UnityFramework is supplied by the flutter_embed_unity_ios pod as a `vendored_framework`). I tried adding these pods to the Runner target of the example project's Podfile, eg:

```
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'Firebase/Core', '10.15.0'
  pod 'Firebase/Crashlytics', '10.15.0'
    
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end
```

However this results in a different error: `Framework not found Pods_UnityFramework`

At this point I'm totally stuck. UnityFramework is included in the `vendored_frameworks` of the flutter_embed_unity_ios podspec - I found that this was the only way to get the flutter_embed_unity_ios plugin to build (because it also depends on UnityFramework). Adding it to `vendors_frameworks` should mean it is available to the project, so I don't know why adding the Firebase pods causes UnityFramework to not be found, or why it refers to it as Pods_UnityFramework and not UnityFramework. I really don't know much about cocoapods / Xcode build systems / linking so I'm totally lost here.

You may have better luck trying [flutter_unity_widget](https://pub.dev/packages/flutter_unity_widget). That uses [a different approach to linking UnityFramework in it's podspec](https://github.com/juicycleff/flutter-unity-view-widget/blob/master/ios/flutter_unity_widget.podspec), it appears to reply on the UnityFramework from the Unity-iPhone project by messing around with FRAMEWORK_SEARCH_PATHS and  OTHER_LDFLAGS
```
s.frameworks = 'UnityFramework'

...

s.xcconfig = {
     'FRAMEWORK_SEARCH_PATHS' => '"${PODS_ROOT}/../UnityLibrary" "${PODS_ROOT}/../.symlinks/flutter/ios-release" "${PODS_CONFIGURATION_BUILD_DIR}"',
     'OTHER_LDFLAGS' => '$(inherited) -framework UnityFramework ${PODS_LIBRARIES}'
  } 
```

To me this looks like maybe a hack, and I suspect this is the reason behind [persistent 'No such module UnityFramework' issues](https://github.com/juicycleff/flutter-unity-view-widget/issues?q=is%3Aissue+is%3Aopen+no+such+module+unityframework+) which I kept getting, which was one of the reasons I made this alternative plugin.

If anyone can help shed light on this issue please ad a comment!

**Comment by Kejiasir** [comment]
Hello, I encountered the same problem. I integrated `Firebase/Crashlytics SDK` in the unity project. When I compiled it into an iOS project, I got an error when I ran it. `Framework 'Pods_UnityFramework' not found`, No solution was found on Google. Is this problem irreparable?

**Comment by timbotimbo** [comment]
@jamesncl 
> After some research I can now reproduce this error with the following steps:
> 
>     1. [Download the Firebase Unity SDK](https://firebase.google.com/docs/unity/setup#add-sdks)
> 
>     2. Open the example Unity project
> 
>     3. In Unity, go to Assets -> Import package -> Custom package, select FirebaseCrashlytics.unityPackage
> 
>     4. In Unity, go to Flutter Embed -> Export project to Flutter app (IOS), and do the [required setup steps from the flutter_embed_unity readme](https://pub.dev/packages/flutter_embed_unity#link-exported-unity-project-to-your-flutter-project)
> 
>     5. Try to build the project - it will fail with build error 'Framework not found FBLPromises'
> 

Following only these steps I reproduced the error `Framework 'Pods_UnityFramework' not found`. 

Here is what I did to get rid of this error:
(I was able to skip this step 1 on a second try).

1. Make sure the Unity pods are installed. 
In the terminal I ran `pod install` in the `ios/unityLibrary` folder.
To be exact, I needed `arch -x86_64 pod install --repo-update` on my M1 mac to get around some cocoapod errors.

    In the terminal it successfully installed ~15 packages like Firebase, FirebaseAnalytics and FirebaseCore.

2. Now I use `Add Files to "Runner"` to add `ios/unityLibrary/Pods.xcodeproj`, just like you have to do with Unity-iPhone.

3. Building the flutter_embed_example now ran into an error about a missing GoogleService-info.plist file.  
This is expected as I didn't actually set up a Firebase project for this test.
I copied a GoogleService file from a random old app to Unity-iPhone and set target membership to UnityFramework.

4. I can now actually run the example with Firebase package on an iPad.  
I don't know if the Firebase stuff works from here on out, as I did not setup a project in the Firebase console website.


Using unity 2022.3.21, Xcode 15.3

**Comment by jamesncl** [comment]
@timbotimbo thanks so much for your help with this. I'll add your solution to the list of common problems in the README.
